version: '3.9'

services:

  db_todo:
    container_name: DB_todo_api
    image: postgres:14.1
    restart: always
    env_file:
      - ../environments/default.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5434:5432"
    networks:
      - production-network-todo
    expose:
      - 5434

  api:
    build:
      dockerfile: api.dockerfile
      context: ../
    container_name: todo_api
    ports:
      - "8010:8000"
    volumes:
      - ../logs:/code/logs
    env_file:
      - ../environments/default.env
    depends_on:
      - db_todo
    networks:
      - production-network-todo
    restart: on-failure:30
    expose:
      - 8000



volumes:
  postgres_data:

networks:
  production-network-todo:
    driver: bridge
